version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: directus_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: directus
      MYSQL_USER: directus_user
      MYSQL_PASSWORD: directus_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
